## History

Givens rotation is a method to obtain the QR decomposition of a matrix.

Givens rotation is a rotation in the plane spanned by two coordinates axes. Givens rotations are named after Wallace Givens, who introduced them to numerical analysts in the 1950s while he was working at Argonne National Laboratory.



$ A\vec{x}  = \vec{b}$

$ A = QR $

$Q = Q_{k}Q_{k-1}Q_{k-2}...Q_{1}$, 
Q is the product of all Givens rotations.

Since Q is orthogonal and symmetric:

$Q^TA = R$

$R\vec{x} = Q^T\vec{b}$

$Q^TA = \begin{bmatrix}cos(t) & -sin(t)\\sin(t) & cos(t)\end{bmatrix}^T * \begin{bmatrix} a\\b\\\end{bmatrix} = \begin{bmatrix} r\\0\\\end{bmatrix}$

## Pseudocode

In [ ]:
"""
Q = I
R = A 
    for j = i:n do
        for i = m: -1: j+1 do
                [c, s] = givens(r[i-1][j], r[i][j])
                R = G(i, j, c, s).T*R
                Q = Q*G(i, j, c, s)
"""

In [576]:
import numpy as np
A = [[0.8147, 0.0975, 0.1576], 
     [0.9058, 0.2785, 0.9706],
     [0.1270, 0.5469, 0.9572],
     [0.9134, 0.9575, 0.4854],
     [0.6324, 0.9649, 0.8003]]

s = sin(t), c = cos(t)

In [577]:
def cs(A, i, j): 
    r = np.hypot(A[i-1][j], A[i][j]) #find hypotenuse between two points in A
    s = A[i][j]/r #find sin(t) for the bottom point
    c = A[i-1][j]/r #find cos(t) for the top point
    
    #because -s*A[i][j] + c*A[i-1][j] = 0, by convention we take c as positive if c is negative
    #and preserve the relationship in the above equation by taking the inverse of s
    if c < 0: 
        c = c*-1
        s = s*-1
    return c, s

def g(c, s, shape, i):
    Q = np.eye(shape) #create identity the same size of A
    Q[i][i], Q[i][i-1], Q[i-1][i], Q[i-1][i-1] = c, s, -s, c #create any Givens rotation matrix given c,s 
    return Q
"""
First Givens rotation matrix:
Q = [[1, 0, 0, 0, 0],
    [0, 1, 0, 0, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 0, cos(t), -sin(t)],
    [0, 0, 0, sin(t), cos(t)]]
    
Second Givens rotation matrix:
Q = [[1, 0, 0, 0, 0],
    [0, 1, 0, 0, 0],
    [0, 0, cos(t), -sin(t), 0],
    [0, 0, sin(t), cos(t), 0],
    [0, 0, 0, 0, 1]]
"""

def givens(A): 
    shape = np.shape(A) #get row and size of A
    Q = np.eye(shape[0]) #initialize Q as an identity with shape of the number of rows in A
    R = A #initialize R as A
    for j in range(shape[1]): #for every column of A
        for i in range(shape[0]-1, j, -1): #for every row in A, counting backwards
            c, s = cs(R, i, j) #get c and s from previous R in the ith and jth column
            G = g(c, s, shape[0], i) #get Givens rotation matrix
            R = np.dot(np.transpose(G), R) #build R
            """
            First R matrix:
            [[0.8147, 0.0975, 0.1576],
            [0.9058, 0.2785, 0.9706],
            [0.1270, 0.5469, 0.9572],
            [1.1109, 1.3365, 0.8546],
            [0, 0.2483, 0.3817]]
            
            Second R matrix:
            [[0.8147, 0.0975, 0.1576],
            [0.9058, 0.2785, 0.9706],
            [1.1181, 1.3899, 0.9578],
            [0, −0.3916, −0.8539],
            [0, 0.2483, 0.3817]]
            """
            Q = np.dot(Q, G) #multiply all Givens rotations to build final Q
    
    return Q,R

In [578]:
givens(A)

(array([[ 0.49266686, -0.48066784,  0.17795345, -0.70325697,  0.        ],
        [ 0.54775702, -0.35834917, -0.57774357,  0.48246545,  0.07062287],
        [ 0.07679967,  0.47543202, -0.63432053, -0.4316598 , -0.42352507],
        [ 0.5523529 ,  0.33905494,  0.48084552,  0.27688497, -0.5216036 ],
        [ 0.38242607,  0.54731202,  0.03114461, -0.09829173,  0.73727105]]),
 array([[  1.65365294e+00,   1.14046791e+00,   1.25697758e+00],
        [  1.00339337e-16,   9.66094882e-01,   6.34107648e-01],
        [  6.47944833e-17,  -1.77623163e-17,  -8.81556607e-01],
        [  8.89699270e-18,  -2.59025629e-17,  -3.04244395e-17],
        [  5.72488704e-19,   7.07168360e-18,  -9.14512140e-18]]))

In [586]:
from numpy import linalg
linalg.qr(A)

(array([[-0.49266686, -0.48066784,  0.17795345],
        [-0.54775702, -0.35834917, -0.57774357],
        [-0.07679967,  0.47543202, -0.63432053],
        [-0.5523529 ,  0.33905494,  0.48084552],
        [-0.38242607,  0.54731202,  0.03114461]]),
 array([[-1.65365294, -1.14046791, -1.25697758],
        [ 0.        ,  0.96609488,  0.63410765],
        [ 0.        ,  0.        , -0.88155661]]))

In [580]:
Q, R = givens(A)

In [581]:
QR = np.dot(Q,R) #this shows the decomposition is true for A
print(QR)
print()
print(A)

[[ 0.8147  0.0975  0.1576]
 [ 0.9058  0.2785  0.9706]
 [ 0.127   0.5469  0.9572]
 [ 0.9134  0.9575  0.4854]
 [ 0.6324  0.9649  0.8003]]

[[0.8147, 0.0975, 0.1576], [0.9058, 0.2785, 0.9706], [0.127, 0.5469, 0.9572], [0.9134, 0.9575, 0.4854], [0.6324, 0.9649, 0.8003]]


In [582]:
eps = 1.0E-10
Q_T = np.transpose(Q) #shows Q is symmetric
identity = np.dot(Q, Q_T)
low_values_indices_identity = identity < eps
identity[low_values_indices_identity] = 0
identity

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [583]:
print(np.dot(Q_T, A)) #this shows Q.T*A = R
print()
print(R)

[[  1.65365294e+00   1.14046791e+00   1.25697758e+00]
 [  1.96850987e-16   9.66094882e-01   6.34107648e-01]
 [  5.26452123e-17   1.37436624e-16  -8.81556607e-01]
 [  5.47781621e-17  -1.58710662e-17   7.75335271e-17]
 [ -9.17113024e-17  -7.61167359e-17  -3.61970943e-18]]

[[  1.65365294e+00   1.14046791e+00   1.25697758e+00]
 [  1.00339337e-16   9.66094882e-01   6.34107648e-01]
 [  6.47944833e-17  -1.77623163e-17  -8.81556607e-01]
 [  8.89699270e-18  -2.59025629e-17  -3.04244395e-17]
 [  5.72488704e-19   7.07168360e-18  -9.14512140e-18]]
